.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-CALC 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
calc \- Evaluate a mathematical expression
.SH SYNOPSIS
\fBcalc\fR [\fB\-\-angles\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIEXPRESSION\fR] 
.SH DESCRIPTION
Evaluate a mathematical expression
.SH OPTIONS
.TP
\fB\-\-angles\fR \fI<ANGLES>\fR [default: rad]
Angle mode: deg or rad
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIEXPRESSION\fR]

