.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-HASH 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
hash \- Generate a hash of input text
.SH SYNOPSIS
\fBhash\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIALGORITHM\fR> [\fIINPUT\fR] 
.SH DESCRIPTION
Generate a hash of input text
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIALGORITHM\fR>

.TP
[\fIINPUT\fR]

