.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-META 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
meta \- Generate HTML meta tags
.SH SYNOPSIS
\fBmeta\fR <\fB\-\-title\fR> <\fB\-\-description\fR> [\fB\-\-url\fR] [\fB\-\-image\fR] [\fB\-\-page\-type\fR] [\fB\-\-site\-name\fR] [\fB\-\-author\fR] [\fB\-\-twitter\-handle\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate HTML meta tags
.SH OPTIONS
.TP
\fB\-\-title\fR \fI<TITLE>\fR

.TP
\fB\-\-description\fR \fI<DESCRIPTION>\fR

.TP
\fB\-\-url\fR \fI<URL>\fR

.TP
\fB\-\-image\fR \fI<IMAGE>\fR

.TP
\fB\-\-page\-type\fR \fI<PAGE_TYPE>\fR [default: website]

.TP
\fB\-\-site\-name\fR \fI<SITE_NAME>\fR

.TP
\fB\-\-author\fR \fI<AUTHOR>\fR

.TP
\fB\-\-twitter\-handle\fR \fI<TWITTER_HANDLE>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
