.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-BASE 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
base \- Convert numbers between bases (dec, hex, oct, bin)
.SH SYNOPSIS
\fBbase\fR [\fB\-\-from\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> [\fITARGETS\fR] 
.SH DESCRIPTION
Convert numbers between bases (dec, hex, oct, bin)
.SH OPTIONS
.TP
\fB\-\-from\fR \fI<FROM>\fR [default: auto]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>

.TP
[\fITARGETS\fR]

