.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-HARMONY 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
harmony \- Generate colour harmonies from a base colour
.SH SYNOPSIS
\fBharmony\fR [\fB\-p\fR|\fB\-\-pretty\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICOLOUR\fR> [\fIHARMONY_TYPE\fR] 
.SH DESCRIPTION
Generate colour harmonies from a base colour
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-pretty\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICOLOUR\fR>

.TP
[\fIHARMONY_TYPE\fR]

