.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-UNIT 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
unit \- Convert between units (length, weight, data, temperature, volume, speed, pressure, time)
.SH SYNOPSIS
\fBunit\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> [\fITARGETS\fR] 
.SH DESCRIPTION
Convert between units (length, weight, data, temperature, volume, speed, pressure, time)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>
Value with unit, e.g. "100kg" or "100 kg"
.TP
[\fITARGETS\fR]
Target unit(s)
