.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-CLIP 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
clip \- Trim transparent edges from a PNG
.SH SYNOPSIS
\fBclip\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIMAGES\fR] 
.SH DESCRIPTION
Trim transparent edges from a PNG
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIMAGES\fR]

