.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-CONTRAST 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
contrast \- Check WCAG contrast ratio between two colours
.SH SYNOPSIS
\fBcontrast\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFG\fR> <\fIBG\fR> 
.SH DESCRIPTION
Check WCAG contrast ratio between two colours
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFG\fR>

.TP
<\fIBG\fR>

