.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-FONT-INFO 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
font\-info \- Extract metadata from a font file (ttf, otf, woff, woff2)
.SH SYNOPSIS
\fBfont\-info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFONT\fR> 
.SH DESCRIPTION
Extract metadata from a font file (ttf, otf, woff, woff2)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFONT\fR>

