.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-WC 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
wc \- Count words, characters, sentences, and reading time
.SH SYNOPSIS
\fBwc\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIINPUT\fR] 
.SH DESCRIPTION
Count words, characters, sentences, and reading time
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIINPUT\fR]

