.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-SHAVIAN 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
shavian \- Transliterate English text to the Shavian alphabet
.SH SYNOPSIS
\fBshavian\fR [\fB\-\-gloss\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIINPUT\fR] 
.SH DESCRIPTION
Transliterate English text to the Shavian alphabet
.SH OPTIONS
.TP
\fB\-\-gloss\fR
Show side\-by\-side gloss (Latin / Shavian / IPA)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIINPUT\fR]

