.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-COMPLETIONS 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
completions \- Generate shell completions
.SH SYNOPSIS
\fBcompletions\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR> 
.SH DESCRIPTION
Generate shell completions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISHELL\fR>

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
bash
.IP \(bu 2
elvish
.IP \(bu 2
fish
.IP \(bu 2
powershell
.IP \(bu 2
zsh
.RE
