.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-REM2PX 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
rem2px \- Convert rem to px
.SH SYNOPSIS
\fBrem2px\fR [\fB\-\-base\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> 
.SH DESCRIPTION
Convert rem to px
.SH OPTIONS
.TP
\fB\-\-base\fR \fI<BASE>\fR [default: 16]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>

