.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-DECODE 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
decode \- Decode text (base64, url)
.SH SYNOPSIS
\fBdecode\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIENCODING\fR> [\fIINPUT\fR] 
.SH DESCRIPTION
Decode text (base64, url)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIENCODING\fR>

.TP
[\fIINPUT\fR]

