.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-PX2REM 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
px2rem \- Convert px to rem
.SH SYNOPSIS
\fBpx2rem\fR [\fB\-\-base\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> 
.SH DESCRIPTION
Convert px to rem
.SH OPTIONS
.TP
\fB\-\-base\fR \fI<BASE>\fR [default: 16]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>

