.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-SPLIT 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
split \- Split an image into a grid of tiles
.SH SYNOPSIS
\fBsplit\fR [\fB\-\-rows\fR] [\fB\-\-cols\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIMAGE\fR> 
.SH DESCRIPTION
Split an image into a grid of tiles
.SH OPTIONS
.TP
\fB\-\-rows\fR \fI<ROWS>\fR [default: 1]

.TP
\fB\-\-cols\fR \fI<COLS>\fR [default: 1]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIMAGE\fR>

