.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-PAPER 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
paper \- Look up paper size dimensions
.SH SYNOPSIS
\fBpaper\fR [\fB\-\-series\fR] [\fB\-\-unit\fR] [\fB\-\-dpi\fR] [\fB\-p\fR|\fB\-\-pixels\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
Look up paper size dimensions
.SH OPTIONS
.TP
\fB\-\-series\fR \fI<SERIES>\fR

.TP
\fB\-\-unit\fR \fI<UNIT>\fR [default: mm]

.TP
\fB\-\-dpi\fR \fI<DPI>\fR [default: 72]

.TP
\fB\-p\fR, \fB\-\-pixels\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR]

