.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-TAILWIND-SHADES 1  "delphitools-cli 0.2.0" "delphitools manual"
.SH NAME
tailwind\-shades \- Generate Tailwind CSS colour shades from a base colour
.SH SYNOPSIS
\fBtailwind\-shades\fR [\fB\-p\fR|\fB\-\-pretty\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICOLOUR\fR> [\fIMODE\fR] 
.SH DESCRIPTION
Generate Tailwind CSS colour shades from a base colour
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-pretty\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICOLOUR\fR>

.TP
[\fIMODE\fR]

